config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'
  get 'events/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :user
    belongs_to :event

    after_create :welcome_sending

    def welcome_sending 
        AttendanceMailer.welcome_attendance(self).deliver_now
    end
end

app/models/event.rb
class Event < ApplicationRecord

    belongs_to :admin, optional: true, class_name: "User"

    has_many :attendances
    has_many :users, through: :attendances, :dependent => :destroy

    validates :start_date,
    presence: true
    validate :start_date_cannot_be_in_the_past

    def start_date_cannot_be_in_the_past
        if start_date.present? && start_date < Date.today
            errors.add(:start_date, "can't be in the past")
        end
    end

    validates :duration,
    presence: true, numericality: {only_integer: true, greater_than: 0},
    format: {with: /\A(\d+)[0,5]\z/, message: "must be a multiple of 5"}

   validates :title, 
   presence: true,
   length: {minimum: 5, maximum: 140}

   validates :description,
   presence: true, 
   length: {minimum: 1, maximum: 1000}

   validates :price,
   presence: true, numericality: {in: 1..1000}

   validates :location, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable,:rememberable, :validatable

    has_many :administrered_events, foreign_key: 'admin_id', class_name: "Event"

    has_many :attendances
    has_many :events, through: :attendances

    after_create :welcome_send

    def welcome_send 
        UserMailer.welcome_email(self).deliver_now
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Jumbotron Template for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/jumbotron/">

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="jumbotron.css" rel="stylesheet">
  </head>


<main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Welcome to EventFreeka</h1>
          <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        </div>
      </div>

      <div class="container">
        <!-- Example row of columns -->
        <div class="row">
        <% @events.each do |event| %>
          <div class="col-md-4">
            <h2><%= event.title %></h2>
            <p><%= event.description %> </p>
            <p><a class="btn btn-primary" href="<%= event_path(event.id) %>" role="button">View details &raquo;</a></p>
          </div>
        <% end %>
        <hr>
      </div> <!-- /container -->

    </main>

    <footer class="container">
      <p>&copy; Edit by TS4A</p>
    </footer>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/layouts/_footer.html.erb
<link rel="stylesheet" href="style.css">

<body>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h4>@ 2023 ETP4A</h4> 
            </div>
            <div class="col-md-4">
                <h4>Nos services</h4>
                <ul>
                    <li> Cours en ligne</li>
                    <li> Formation à distance</li>
                </ul>
            </div>
            <div class="col-md-4">
                <h4>Nos contacts</h4>
                <p>E-mail : etp4a@gmail.com</p>
            </div>
        </div>
    </div>
</footer>
</body>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
<div class="container-fluid">
      <a class="navbar-brand" href="#">EventFreeka</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= root_path%>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">New event</a>
        </li>
        <li class="nav-item dropdown">
        <% if user_signed_in? %>
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Bonjour <%= current_user.first_name %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li class="dropdown-item"><%= link_to "My profil", edit_user_registration_path %></li>
            <li class="dropdown-item">
              <%= form_tag destroy_user_session_path, method: :delete, class:'logout-form' do %>
              <%= submit_tag 'Sign out'%> 
              <% end %>
            </li>
          </ul>
        <% else %>
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Profile
          </a>
        <% end %>
        </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li class="dropdown-item"><%= link_to "Sign Up", new_user_registration_path %></li>
            <li class="dropdown-item"><%= link_to "Sign In", new_user_session_path %></li>
          </ul>
      </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-info" type="submit">Search</button>
      </form>
  </div>
  </div>
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
      <a class="navbar-brand" href="<%= root_path%>">EventFreeka</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= root_path%>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">New event</a>
        </li>
        <li class="nav-item dropdown">
        <% if user_signed_in? %>
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Bonjour <%= current_user.first_name %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li class="dropdown-item"><%= link_to "My profil", edit_user_registration_path %></li>
            <li class="dropdown-item">
              <%= form_tag destroy_user_session_path, method: :delete, class:'logout-form' do %>
              <%= submit_tag 'Sign out'%> 
              <% end %>
            </li>
          </ul>
        <% else %>
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Profile
          </a>
        <% end %>
        </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li class="dropdown-item"><%= link_to "Sign Up", new_user_registration_path %></li>
            <li class="dropdown-item"><%= link_to "Sign In", new_user_session_path %></li>
          </ul>
      </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
  </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventFreeka</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--<link rel="stylesheet" href="style.css"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script> 
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>